#!/bin/bash

noise () {

    # fill luks container partition with noise (takes a long time for larger partitions)
    sudo openssl enc -aes-256-ctr -pass pass:"$(dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64)" -nosalt < /dev/zero > /dev/$1$2

}

preinstall() {

    ### setup luks

    sudo cryptsetup luksFormat /dev/$1$2
    sudo cryptsetup luksOpen /dev/$1$2 lvm

    ### setup lvm in luks

    sudo pvcreate /dev/mapper/lvm
    sudo vgcreate lvm /dev/mapper/lvm
    sudo lvcreate -n swap -L 4G lvm
    sudo lvcreate -n root -L 100G lvm
    sudo lvcreate -n home -L 100G lvm

}

postinstall() {

    ### mount and chroot to new install 

    # Mount root partition: 
    sudo mount /dev/mapper/lvm-root /mnt

    # Mount your virtual filesystems:
    for i in /dev /dev/pts /proc /sys /run; do sudo mount -B $i /mnt$i; done

    # chroot to fresh install
    sudo cp lvm-on-luks /mnt/lvm-on-luks
    sudo cp crypto_keyfile /mnt/crypto_keyfile	

    sudo chroot /mnt sudo bash lvm-on-luks $1 $2 post2

}

postinstall2() {

    ### configure grub 
    
    sudo echo "GRUB_ENABLE_CRYPTODISK=y" >> /etc/default/grub
    sudo echo "GRUB_CMDLINE_LINUX=\"cryptdevice=$(blkid -s UUID -o value /dev/$2$3):lvm\""  >> /etc/default/grub
    sudo grub-mkconfig -o /boot/grub/grub.cfg
    sudo grub-install /dev/$1

    ### add luks to crypttab

    # make a new key and add it to the luks container
    sudo dd bs=512 count=4 if=/dev/urandom of=/crypto_keyfile.bin
    sudo cryptsetup luksAddKey /dev/$1$2 /crypto_keyfile.bin

    # copy the script which will add the key file to initram and make executable
    sudo cp crypto_keyfile /etc/initramfs-tools/hooks/crypto_keyfile
    sudo chmod +x /etc/initramfs-tools/hooks/crypto_keyfile

    # update cryptab with uuid of drive and details for keyfile decryption
    sudo echo "lvm UUID=$(blkid -s UUID -o value /dev/$1$2) /crypto_keyfile.bin luks,keyscript=/bin/cat" > /etc/crypttab

    # update ramdisk
    sudo update-initramfs -u

    ### cleanup and secure new boot and keyfile. run in new install

    sudo chmod 000 /crypto_keyfile.bin
    sudo chmod -R g-rwx,o-rwx /boot

    # remove ubiquity if its still there due to crash installer crash (?)
    sudo apt-get -y remove ubiquity

    sudo rm lvm-on-luks crypto_keyfile

}

if [[ "$#" -ne 3 ]]
then
    echo "you should have arguments: sdx y command"
    exit
fi

if [ $3 == "noise" ]
then
    noise $1 $2
fi

if [ $3 == "pre" ]
then
    preinstall $1 $2
fi

if [ $3 == "post" ]
then
    postinstall $1 $2
fi

if [ $3 == "post2" ]
then
    postinstall2 $1 $2
fi